# Generated by Django 5.2.6 on 2025-09-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='credits',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsmodel',
            name='firstName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsmodel',
            name='lastName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
