# Generated by Django 5.2.6 on 2025-09-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userdetailsmodel_credits_userdetailsmodel_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
