# Generated by Django 5.2.6 on 2025-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_rename_firstname_userdetailsmodel_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='credits',
            new_name='carousel_credits',
        ),
        migrations.RenameField(
            model_name='userdetailsmodel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userdetailsmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdetailsmodel',
            name='grid_credits',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
