# Generated by Django 5.2.6 on 2025-10-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_rename_credits_userdetailsmodel_carousel_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='email',
            field=models.EmailField(default='aman@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailsmodel',
            name='phone_number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
