# Generated by Django 5.2.6 on 2025-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('opt_method', models.CharField(choices=[('EMAIL', 'Email')], max_length=256)),
                ('otp_value', models.CharField(max_length=256)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Registration')], max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eamil', models.EmailField(max_length=254)),
            ],
        ),
    ]
