# Generated by Django 5.2.6 on 2025-09-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverificationmodel',
            old_name='eamil',
            new_name='email',
        ),
    ]
