# Generated by Django 5.2.6 on 2025-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_rename_eamil_otpverificationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverificationmodel',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'registration'), ('PASSWORD_RESET', 'password_reset')], max_length=256),
        ),
    ]
